import type {ConnectivityMqttPhase, ConnectivityOcppPhase} from './types';

/**
 * Identifikátory 15 podlogík CONNECTIVITY karty.
 * Používajú sa v logoch na jednoznačnú identifikáciu bežiacej fázy
 * a ako jediný zdroj pravdy pre sledovanie stavu MQTT a OCPP konektivity.
 */
export const CONNECTIVITY_PHASE = {
  /** Čakanie na bootstrap connection údaje (URL, credentials) */
  WAIT_BOOTSTRAP: 'CONNECTIVITY_WAIT_BOOTSTRAP',
  /** Bootstrap údaje existujú, internet nedostupný */
  WAIT_INTERNET: 'CONNECTIVITY_WAIT_INTERNET',

  /** Pokus o MQTT pripojenie podľa bootstrap URL */
  MQTT_CONNECT_ATTEMPT: 'MQTT_CONNECT_ATTEMPT',
  /** MQTT connect policy: bez retain, bez persistent session, QoS 0 */
  MQTT_CONNECT_POLICY: 'MQTT_CONNECT_POLICY',
  /** MQTT úspešne pripojené, subscribe aktívny */
  MQTT_CONNECTED_STATE: 'MQTT_CONNECTED_STATE',
  /** MQTT connect zlyhal, beží 5-minútový backoff */
  MQTT_CONNECT_ERROR: 'MQTT_CONNECT_ERROR',
  /** Backoff uplynul, spúšťa sa ďalší MQTT connect pokus */
  MQTT_RECONNECT_AFTER_BACKOFF: 'MQTT_RECONNECT_AFTER_BACKOFF',
  /** MQTT spojenie stratené počas behu */
  MQTT_CONNECTION_LOST: 'MQTT_CONNECTION_LOST',

  /** Pokus o OCPP websocket pripojenie podľa bootstrap URL */
  OCPP_CONNECT_ATTEMPT: 'OCPP_CONNECT_ATTEMPT',
  /** OCPP úspešne pripojené */
  OCPP_CONNECTED_STATE: 'OCPP_CONNECTED_STATE',
  /** OCPP connect zlyhal, beží 5-minútový backoff */
  OCPP_CONNECT_ERROR: 'OCPP_CONNECT_ERROR',
  /** Backoff uplynul, spúšťa sa ďalší OCPP connect pokus */
  OCPP_RECONNECT_AFTER_BACKOFF: 'OCPP_RECONNECT_AFTER_BACKOFF',
  /** OCPP spojenie stratené počas behu */
  OCPP_CONNECTION_LOST: 'OCPP_CONNECTION_LOST',

  /** Pravidlo: 5-minútový backoff po neúspešnom connecte */
  BACKOFF_RULE: 'CONNECTIVITY_BACKOFF_RULE',
  /** Pravidlo: protokol a port sa berú z URL */
  URL_DRIVEN_PROTOCOL: 'CONNECTIVITY_URL_DRIVEN_PROTOCOL',
} as const;

export type ConnectivityPhase =
  (typeof CONNECTIVITY_PHASE)[keyof typeof CONNECTIVITY_PHASE];

/** Backoff interval po neúspešnom connecte (ms) — 5 minút. */
export const CONNECTIVITY_BACKOFF_INTERVAL_MS = 5 * 60 * 1000;

/** Prefix pre logovanie CONNECTIVITY logiky. */
export const CONNECTIVITY_LOG_PREFIX = '[CONNECTIVITY]' as const;

/** Formátuje log s aktuálnou fázou: `[CONNECTIVITY][MQTT_CONNECT_ATTEMPT] message` */
export const connectivityPhaseLog = (
  phase: ConnectivityPhase,
  ...args: unknown[]
): void => {
  console.log(`${CONNECTIVITY_LOG_PREFIX}[${phase}]`, ...args);
};

/**
 * Povolené prechody MQTT track-u.
 * Kľúč = zdrojová fáza, hodnota = pole povolených cieľových fáz.
 */
export const MQTT_TRANSITIONS: Readonly<
  Record<ConnectivityMqttPhase, readonly ConnectivityMqttPhase[]>
> = {
  [CONNECTIVITY_PHASE.WAIT_BOOTSTRAP]: [
    CONNECTIVITY_PHASE.WAIT_INTERNET,
    CONNECTIVITY_PHASE.MQTT_CONNECT_ATTEMPT,
    CONNECTIVITY_PHASE.MQTT_CONNECT_ERROR,
  ],
  [CONNECTIVITY_PHASE.WAIT_INTERNET]: [
    CONNECTIVITY_PHASE.MQTT_CONNECT_ATTEMPT,
    CONNECTIVITY_PHASE.MQTT_CONNECT_ERROR,
    CONNECTIVITY_PHASE.WAIT_BOOTSTRAP,
  ],
  [CONNECTIVITY_PHASE.MQTT_CONNECT_ATTEMPT]: [
    CONNECTIVITY_PHASE.MQTT_CONNECTED_STATE,
    CONNECTIVITY_PHASE.MQTT_CONNECT_ERROR,
    CONNECTIVITY_PHASE.WAIT_INTERNET,
    CONNECTIVITY_PHASE.WAIT_BOOTSTRAP,
  ],
  [CONNECTIVITY_PHASE.MQTT_CONNECTED_STATE]: [
    CONNECTIVITY_PHASE.MQTT_CONNECTION_LOST,
    CONNECTIVITY_PHASE.WAIT_INTERNET,
    CONNECTIVITY_PHASE.WAIT_BOOTSTRAP,
  ],
  [CONNECTIVITY_PHASE.MQTT_CONNECT_ERROR]: [
    CONNECTIVITY_PHASE.MQTT_RECONNECT_AFTER_BACKOFF,
    CONNECTIVITY_PHASE.MQTT_CONNECTED_STATE,
    CONNECTIVITY_PHASE.WAIT_INTERNET,
    CONNECTIVITY_PHASE.WAIT_BOOTSTRAP,
  ],
  [CONNECTIVITY_PHASE.MQTT_RECONNECT_AFTER_BACKOFF]: [
    CONNECTIVITY_PHASE.MQTT_CONNECT_ATTEMPT,
    CONNECTIVITY_PHASE.MQTT_CONNECTED_STATE,
    CONNECTIVITY_PHASE.WAIT_INTERNET,
    CONNECTIVITY_PHASE.WAIT_BOOTSTRAP,
  ],
  [CONNECTIVITY_PHASE.MQTT_CONNECTION_LOST]: [
    CONNECTIVITY_PHASE.MQTT_RECONNECT_AFTER_BACKOFF,
    CONNECTIVITY_PHASE.MQTT_CONNECTED_STATE,
    CONNECTIVITY_PHASE.WAIT_INTERNET,
    CONNECTIVITY_PHASE.WAIT_BOOTSTRAP,
  ],
};

/**
 * Povolené prechody OCPP track-u.
 */
export const OCPP_TRANSITIONS: Readonly<
  Record<ConnectivityOcppPhase, readonly ConnectivityOcppPhase[]>
> = {
  [CONNECTIVITY_PHASE.WAIT_BOOTSTRAP]: [
    CONNECTIVITY_PHASE.WAIT_INTERNET,
    CONNECTIVITY_PHASE.OCPP_CONNECT_ATTEMPT,
    CONNECTIVITY_PHASE.OCPP_CONNECT_ERROR,
  ],
  [CONNECTIVITY_PHASE.WAIT_INTERNET]: [
    CONNECTIVITY_PHASE.OCPP_CONNECT_ATTEMPT,
    CONNECTIVITY_PHASE.OCPP_CONNECT_ERROR,
    CONNECTIVITY_PHASE.WAIT_BOOTSTRAP,
  ],
  [CONNECTIVITY_PHASE.OCPP_CONNECT_ATTEMPT]: [
    CONNECTIVITY_PHASE.OCPP_CONNECTED_STATE,
    CONNECTIVITY_PHASE.OCPP_CONNECT_ERROR,
    CONNECTIVITY_PHASE.WAIT_INTERNET,
    CONNECTIVITY_PHASE.WAIT_BOOTSTRAP,
  ],
  [CONNECTIVITY_PHASE.OCPP_CONNECTED_STATE]: [
    CONNECTIVITY_PHASE.OCPP_CONNECTION_LOST,
    CONNECTIVITY_PHASE.WAIT_INTERNET,
    CONNECTIVITY_PHASE.WAIT_BOOTSTRAP,
  ],
  [CONNECTIVITY_PHASE.OCPP_CONNECT_ERROR]: [
    CONNECTIVITY_PHASE.OCPP_RECONNECT_AFTER_BACKOFF,
    CONNECTIVITY_PHASE.OCPP_CONNECTED_STATE,
    CONNECTIVITY_PHASE.WAIT_INTERNET,
    CONNECTIVITY_PHASE.WAIT_BOOTSTRAP,
  ],
  [CONNECTIVITY_PHASE.OCPP_RECONNECT_AFTER_BACKOFF]: [
    CONNECTIVITY_PHASE.OCPP_CONNECT_ATTEMPT,
    CONNECTIVITY_PHASE.OCPP_CONNECTED_STATE,
    CONNECTIVITY_PHASE.WAIT_INTERNET,
    CONNECTIVITY_PHASE.WAIT_BOOTSTRAP,
  ],
  [CONNECTIVITY_PHASE.OCPP_CONNECTION_LOST]: [
    CONNECTIVITY_PHASE.OCPP_RECONNECT_AFTER_BACKOFF,
    CONNECTIVITY_PHASE.OCPP_CONNECTED_STATE,
    CONNECTIVITY_PHASE.WAIT_INTERNET,
    CONNECTIVITY_PHASE.WAIT_BOOTSTRAP,
  ],
};
